/* CREER UN UTILISATEUR */
CREATE USER 'toto'@'localhost' IDENTIFIED BY 'azerty';

/* ACCORDER TOUS LES PRIVILEGES A TOTO */
GRANT ALL PRIVILEGES ON rezo_social.* TO 'toto'@'localhost';
GRANT ALL PRIVILEGES ON mini_faq.* TO 'toto'@'localhost';

/* RECHARGER LES PRIVILEGES AU NIVEAU DU SERVEUR */
FLUSH PRIVILEGES;